### ISSUE TITLE
btcli.o make target fails

### ISSUE THREAD

**Issue by zzggbb** [Koushien/btpd#1]
```
cli/btcli.c: In function 'bytestostr':
cli/btcli.c:58:6: error: 'siunits' undeclared (first use in this function)
  if (siunits) {
      ^
cli/btcli.c:58:6: note: each undeclared identifier is reported only once for each function it appears in
cli/btcli.c: In function 'print_size':
cli/btcli.c:85:16: error: too few arguments to function 'bytestostr'
  printf("%s ", bytestostr(size), (1 << 10));
                ^
cli/btcli.c:48:7: note: declared here
 char *bytestostr(double bytes, double prefix)
       ^
Makefile:687: recipe for target 'cli/btcli.o' failed
make: *** [cli/btcli.o] Error 1
```

**Comment by Koushien** [comment]
After thinking about this for awhile now, I've decided to revert the offending commit. While I like the intended functionality (choosing between scaling SI or IEC units), when correcting I felt I was precariously compromising between getting the pushed code to work and trying to make it fit in with the rest of the codebase. Since it was going to take considerable work to achieve what I wanted anyway, I abandoned my current efforts. If this functionality is important to you, I'll make it a priority to develop another solution, otherwise this should now build correctly using

```
# autoreconf -i
# ./configure
# make
# make install
```
